updated
Signed-off-by: sownak.roy <sownak.roy@cgi.com>

diff --git a/platforms/hyperledger-fabric/charts/fabric-external-chaincode/templates/deployment.yaml b/platforms/hyperledger-fabric/charts/fabric-external-chaincode/templates/deployment.yaml
--- a/platforms/hyperledger-fabric/charts/fabric-external-chaincode/templates/deployment.yaml
+++ b/platforms/hyperledger-fabric/charts/fabric-external-chaincode/templates/deployment.yaml
@@ -47,27 +47,38 @@ spec:
       imagePullSecrets:
         - name: {{ .Values.image.pullSecret }}
       {{- end }}
-    {{ if .Values.chaincode.tls }}
       volumes:
-      {{ if .Values.global.vault.tls  }}
+      {{- if .Values.global.vault.tls }}
       - name: vaultca
         secret:
           secretName: {{ .Values.global.vault.tls }}
           items:
           - key: ca.crt.pem
             path: ca-certificates.crt
-      {{ end  }}
+      {{- end }}
       - name: certificates
         emptyDir:
           medium: Memory
       - name: scripts-volume
         configMap:
           name: bevel-vault-script
+      - name: package-manager
+        configMap:
+          name: package-manager
       initContainers:
+      {{- if .Values.chaincode.tls }}
+      # Init container to retrieve TLS certificates for chaincode server
       - name: certificates-init
         image: {{ .Values.image.alpineutils }}
         imagePullPolicy: IfNotPresent
         env:
+        - name: CHAINCODE_NAME
+          value: "{{ .Values.chaincode.name }}"
+        - name: CHAINCODE_VERSION
+          value: "{{ .Values.chaincode.version }}"
+        - name: COMPONENT_NAME
+          value: "{{ .Release.Namespace }}"
+        {{- if eq .Values.global.vault.type "hashicorp" }}
         - name: VAULT_ADDR
           value: {{ .Values.global.vault.address }}
         - name: VAULT_SECRET_ENGINE
@@ -78,32 +89,41 @@ spec:
           value: {{ .Values.global.vault.authPath }}
         - name: VAULT_APP_ROLE
           value: {{ .Values.global.vault.role }}
-        - name: MOUNT_PATH
-          value: /secret
-        - name: CHAINCODE_TLS_ENABLED
-          value: "{{ .Values.chaincode.tls }}"
         - name: VAULT_TYPE
           value: "{{ .Values.global.vault.type }}"
+        {{- if .Values.global.vault.tls }}
+        - name: VAULT_CACERT
+          value: /opt/vault/tls/ca-certificates.crt
+        {{- else }}
+        - name: VAULT_SKIP_VERIFY
+          value: "true"
+        {{- end }}
+        {{- end }}
+        - name: MOUNT_PATH
+          value: /secret
         command: ["sh", "-c"]
         args:
         - |-
           #!/usr/bin/env sh
-{{- if eq .Values.global.vault.type "hashicorp" }}
-          . /scripts/bevel-vault.sh
-
-          vaultBevelFunc "init"
-          function getChaincodeTlsSecret {
-            KEY=$1-xxx
+          set -e
           
-            echo "Getting chaincode certificates from Vault"
-            vaultBevelFunc "readJson" "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/peers/${KEY}"
+          {{- if eq .Values.global.vault.type "hashicorp" }}
+          . /scripts/bevel-vault.sh
+          vaultBevelFunc "init"
+          
+          function getChaincodeTlsSecret {
+            SERVER_USER="${CHAINCODE_NAME}-${CHAINCODE_VERSION}@${COMPONENT_NAME}"
+            TLS_KEY="${SERVER_USER}-tls"
+            
+            echo "Getting chaincode server TLS certificates from Vault for ${TLS_KEY}"
+            vaultBevelFunc "readJson" "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/chaincodes/${TLS_KEY}"
             if [ "$SECRETS_AVAILABLE" == "yes" ]
             then
-              CACERT=$(echo ${VAULT_SECRET} | jq -r '.["ca.crt"]')
-              CLIENT_CERT=$(echo ${VAULT_SECRET} | jq -r '.["client.crt"]')
-              CLIENT_KEY=$(echo ${VAULT_SECRET} | jq -r '.["client.key"]')
+              CA_CERT=$(echo ${VAULT_SECRET} | jq -r '.["ca_crt"]' | sed 's/\\n/\n/g')
+              CLIENT_CERT=$(echo ${VAULT_SECRET} | jq -r '.["client_crt"]' | sed 's/\\n/\n/g')
+              CLIENT_KEY=$(echo ${VAULT_SECRET} | jq -r '.["client_key"]' | sed 's/\\n/\n/g')
 
-              echo "${CACERT}" > ${MOUNT_PATH}/ca.crt
+              echo "${CA_CERT}" > ${MOUNT_PATH}/ca.crt
               echo "${CLIENT_CERT}" > ${MOUNT_PATH}/client.crt
               echo "${CLIENT_KEY}" > ${MOUNT_PATH}/client.key
               CC_TLS_SECRET=true
@@ -111,82 +131,89 @@ spec:
               CC_TLS_SECRET=false
             fi
           }
-{{- else }}
+          {{- else }}
           function getChaincodeTlsSecret {
-            KEY=$1-xxx
-            KUBENETES_SECRET=$(kubectl get secret ${KEY} --namespace {{ .Release.Namespace }} -o json)
-            if  [ "$KUBENETES_SECRET" = "" ]; then
-              CC_TLS_SECRET=false
-            else
-              TLS_CA_CERT=$(echo ${KUBENETES_SECRET} | jq -r '.data.cacrt'  | base64 -d)
-              TLS_SERVER_CERT=$(echo ${KUBENETES_SECRET} | jq -r '.data.servercrt'  | base64 -d)
-              TLS_SERVER_KEY=$(echo ${KUBENETES_SECRET} | jq -r '.data.serverkey'  | base64 -d)
+            SERVER_USER="${CHAINCODE_NAME}-${CHAINCODE_VERSION}@${COMPONENT_NAME}"
+            TLS_KEY="${SERVER_USER}-tls"
+            
+            echo "Getting chaincode server TLS certificates from Kubernetes secret ${TLS_KEY}"
+            if kubectl get secret ${TLS_KEY} --namespace {{ .Release.Namespace }} >/dev/null 2>&1; then
+              TLS_CA_CERT=$(kubectl get secret ${TLS_KEY} --namespace {{ .Release.Namespace }} -o jsonpath='{.data.cacrt}' | base64 -d)
+              TLS_CLIENT_CERT=$(kubectl get secret ${TLS_KEY} --namespace {{ .Release.Namespace }} -o jsonpath='{.data.clientcrt}' | base64 -d)
+              TLS_CLIENT_KEY=$(kubectl get secret ${TLS_KEY} --namespace {{ .Release.Namespace }} -o jsonpath='{.data.clientkey}' | base64 -d)
               
               echo "${TLS_CA_CERT}" > ${MOUNT_PATH}/ca.crt
-              echo "${TLS_SERVER_CERT}" > ${MOUNT_PATH}/server.crt
-              echo "${TLS_SERVER_KEY}" > ${MOUNT_PATH}/server.key
+              echo "${TLS_CLIENT_CERT}" > ${MOUNT_PATH}/client.crt
+              echo "${TLS_CLIENT_KEY}" > ${MOUNT_PATH}/client.key
               CC_TLS_SECRET=true
+            else
+              CC_TLS_SECRET=false
             fi
           }
-{{- end }}
+          {{- end }}
+          
           COUNTER=1
-          while [ "$COUNTER" -le {{ .Values.chaincode.healthCheck.retries }} ]
+          while [ "$COUNTER" -le {{ .Values.chaincode.healthCheck.retries | default 5 }} ]
           do
             mkdir -p ${MOUNT_PATH}
-            getChaincodeTlsSecret ${PEER_NAME}
+            getChaincodeTlsSecret
 
             if [ "$CC_TLS_SECRET" = "true" ]
             then
-              echo "Chaincode certificates have been obtained correctly"
+              echo "Chaincode server TLS certificates have been obtained correctly"
               break
             else
-              echo "Chaincode certificates have not been obtained, sleeping for {{ .Values.chaincode.healthCheck.sleepTimeAfterError }}"
-              sleep {{ .Values.chaincode.healthCheck.sleepTimeAfterError }}
+              echo "Chaincode server TLS certificates have not been obtained, sleeping for {{ .Values.chaincode.healthCheck.sleepTimeAfterError | default 30 }}"
+              sleep {{ .Values.chaincode.healthCheck.sleepTimeAfterError | default 30 }}
               COUNTER=`expr "$COUNTER" + 1`
             fi
           done
 
-          if [ "$COUNTER" -gt {{ .Values.chaincode.healthCheck.retries }} ]
+          if [ "$COUNTER" -gt {{ .Values.chaincode.healthCheck.retries | default 5 }} ]
           then
-            echo "Retry attempted `expr $COUNTER - 1` times, The peer certificates have not been obtained."
+            echo "Retry attempted `expr $COUNTER - 1` times, The chaincode server TLS certificates have not been obtained."
             exit 1
           fi
         volumeMounts:
-        {{ if .Values.global.vault.tls  }}
+        {{- if .Values.global.vault.tls }}
         - name: vaultca
           mountPath: "/etc/ssl/certs/"
           readOnly: true
-        {{ end }}
+        {{- end }}
         - name: certificates
           mountPath: /secret
         - name: scripts-volume
           mountPath: /scripts/bevel-vault.sh
           subPath: bevel-vault.sh
-    {{ end }}
+      {{- end }}
+      
       containers:
         - name: chaincode
           image: {{ .Values.image.external_chaincode }}
           imagePullPolicy: Always
           env:
             - name: CHAINCODE_ID
-              value: "{{ .Values.chaincode.ccid }}"
+              valueFrom:
+                secretKeyRef:
+                  name: "{{ .Values.chaincode.name }}_{{ .Values.chaincode.version }}-package-id"
+                  key: package_id
             - name: CHAINCODE_SERVER_ADDRESS
               value: "0.0.0.0:7052"
             - name: CHAINCODE_TLS_DISABLED
               value: "{{ not .Values.chaincode.tls }}"
-          {{ if .Values.chaincode.tls }}
+            {{- if .Values.chaincode.tls }}
             - name: CHAINCODE_TLS_KEY
-              value: "{{ .Values.chaincode.crypto_mount_path }}/client.key"
+              value: "{{ .Values.chaincode.crypto_mount_path | default "/crypto" }}/client.key"
             - name: CHAINCODE_TLS_CERT
-              value: "{{ .Values.chaincode.crypto_mount_path }}/client.crt"
+              value: "{{ .Values.chaincode.crypto_mount_path | default "/crypto" }}/client.crt"
             - name: CHAINCODE_CLIENT_CA_CERT
-              value: "{{ .Values.chaincode.crypto_mount_path }}/ca.crt"
-          {{ end }}
+              value: "{{ .Values.chaincode.crypto_mount_path | default "/crypto" }}/ca.crt"
+            {{- end }}
           ports:
             - containerPort: 7052
-          {{ if .Values.chaincode.tls }}
+          {{- if .Values.chaincode.tls }}
           volumeMounts:
           - name: certificates
-            mountPath: {{ .Values.chaincode.crypto_mount_path }}
+            mountPath: {{ .Values.chaincode.crypto_mount_path | default "/crypto" }}
             readOnly: true
-          {{ end }}
+          {{- end }}
diff --git a/platforms/hyperledger-fabric/charts/fabric-external-chaincode/templates/package-chaincode.yaml b/platforms/hyperledger-fabric/charts/fabric-external-chaincode/templates/package-chaincode.yaml
--- a/platforms/hyperledger-fabric/charts/fabric-external-chaincode/templates/package-chaincode.yaml
+++ b/platforms/hyperledger-fabric/charts/fabric-external-chaincode/templates/package-chaincode.yaml
@@ -56,7 +56,7 @@ spec:
       {{- end }}
       containers:
         - name: package-chaincode
-          image: {{ .Values.image.fabrictools }}
+          image: {{ .Values.image.fabrictools }}:{{ .Values.global.version }}
           imagePullPolicy: IfNotPresent
           env:
           - name: CHAINCODE_NAME
@@ -78,9 +78,9 @@ spec:
           - name: COMPONENT_NAME
             value: "{{ .Release.Namespace }}"
           - name: ORG_NAME
-            value: "{{ .Values.peer.localmspid | lower | replace "msp" "" }}"
+            value: "{{ .Values.certs.orgData.orgName }}"
           - name: FABRIC_LOGGING_SPEC
-            value: "{{ .Values.peer.loglevel | default "info" }}"
+            value: "{{ .Values.peer.loglevel }}"
           - name: CORE_PEER_TLS_ENABLED
             value: "{{ .Values.peer.tlsstatus }}"
           - name: CORE_PEER_LOCALMSPID
@@ -148,7 +148,7 @@ spec:
               {{- if eq .Values.global.vault.type "hashicorp" }}
               # Check vault for existing package
               PACKAGE_EXISTS="false"
-              vaultBevelFunc 'readJson' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/chaincodes/${CHAINCODE_NAME}/package/v${CHAINCODE_VERSION}"
+              vaultBevelFunc 'readJson' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/chaincodes/${CHAINCODE_NAME}/v${CHAINCODE_VERSION}/package"
               if [ "$SECRETS_AVAILABLE" = "yes" ]; then
                 echo "Package already exists in vault"
                 PACKAGE_EXISTS="true"
@@ -270,7 +270,7 @@ spec:
                 # Store package in vault or Kubernetes secret
                 {{- if eq .Values.global.vault.type "hashicorp" }}
                 echo "Storing package in vault..."
-                PACKAGE_VAULT_ADDR="${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/chaincodes/${CHAINCODE_NAME}/package/v${CHAINCODE_VERSION}"
+                PACKAGE_VAULT_ADDR="${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/chaincodes/${CHAINCODE_NAME}/v${CHAINCODE_VERSION}/package"
                 PACKAGE_B64=$(cat ${PACKAGE_NAME}.tgz | base64 -w 0)
                 echo "{\"data\":{\"package-base64\":\"${PACKAGE_B64}\"}}" > package_payload.json
                 vaultBevelFunc 'write' "${PACKAGE_VAULT_ADDR}" 'package_payload.json'
@@ -289,26 +289,39 @@ spec:
               
               # Check if chaincode is already installed
               echo "Checking if chaincode is already installed..."
-              PEER_POD=$(kubectl get pods -n {{ .Release.Namespace }} -l app={{ .Values.peer.name }} -o jsonpath='{.items[0].metadata.name}')
-              if [ -z "$PEER_POD" ]; then
-                echo "Error: Peer pod not found"
-                exit 1
-              fi
               
-              # Check installed chaincodes
-              INSTALLED_CC=$(kubectl exec -n {{ .Release.Namespace }} $PEER_POD -c {{ .Values.peer.name }} -- \
-                peer lifecycle chaincode queryinstalled -O json | \
+              # Check installed chaincodes using peer CLI directly
+              INSTALLED_CC=$(peer lifecycle chaincode queryinstalled -O json | \
                 jq -r --arg label "${PACKAGE_NAME}" '.installed_chaincodes[]? | select(.label==$label) | .package_id' || echo "")
               
               if [ -n "$INSTALLED_CC" ]; then
                 echo "Chaincode ${PACKAGE_NAME} is already installed with package ID: $INSTALLED_CC"
+                
+                # Store the package ID for future reference if not already stored
+                {{- if eq .Values.global.vault.type "hashicorp" }}
+                # Check if package ID already exists in vault
+                vaultBevelFunc 'readJson' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/chaincodes/${CHAINCODE_NAME}/v${CHAINCODE_VERSION}/package_id"
+                if [ "$SECRETS_AVAILABLE" != "yes" ]; then
+                  echo "Storing existing package ID in vault..."
+                  echo "{\"data\":{\"package_id\":\"${INSTALLED_CC}\"}}" > package_id_payload.json
+                  vaultBevelFunc 'write' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/chaincodes/${CHAINCODE_NAME}/v${CHAINCODE_VERSION}/package_id" 'package_id_payload.json'
+                fi
+                {{- else }}
+                # Check if package ID secret already exists
+                if ! kubectl get secret --namespace {{ .Release.Namespace }} ${PACKAGE_NAME}-package-id >/dev/null 2>&1; then
+                  echo "Storing existing package ID in Kubernetes secret..."
+                  kubectl create secret generic ${PACKAGE_NAME}-package-id \
+                    --namespace {{ .Release.Namespace }} \
+                    --from-literal=package_id="${INSTALLED_CC}"
+                fi
+                {{- end }}
               else
                 echo "Installing chaincode package..."
                 
-                # Get the package from storage and install
+                # Get the package from storage
                 {{- if eq .Values.global.vault.type "hashicorp" }}
                 # Get package from vault
-                vaultBevelFunc 'readJson' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/chaincodes/${CHAINCODE_NAME}/package/v${CHAINCODE_VERSION}"
+                vaultBevelFunc 'readJson' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/chaincodes/${CHAINCODE_NAME}/v${CHAINCODE_VERSION}/package"
                 if [ "$SECRETS_AVAILABLE" = "yes" ]; then
                   echo "${VAULT_SECRET}" | jq -r ".\"package-base64\"" | base64 -d > /tmp/${PACKAGE_NAME}.tgz
                 else
@@ -320,16 +333,19 @@ spec:
                 kubectl get secret --namespace {{ .Release.Namespace }} ${PACKAGE_NAME}-package -o jsonpath='{.data.package}' | base64 -d > /tmp/${PACKAGE_NAME}.tgz
                 {{- end }}
                 
-                # Copy package to peer pod and install
-                kubectl cp /tmp/${PACKAGE_NAME}.tgz {{ .Release.Namespace }}/$PEER_POD:/opt/gopath/src/github.com/hyperledger/fabric/${PACKAGE_NAME}.tgz -c {{ .Values.peer.name }}
+                # Verify package file exists
+                if [ ! -f "/tmp/${PACKAGE_NAME}.tgz" ]; then
+                  echo "Error: Package file not found after retrieval"
+                  exit 1
+                fi
                 
-                # Install the chaincode
-                kubectl exec -n {{ .Release.Namespace }} $PEER_POD -c {{ .Values.peer.name }} -- \
-                  peer lifecycle chaincode install ${PACKAGE_NAME}.tgz
+                # Install the chaincode using peer CLI directly
+                echo "Installing chaincode package: ${PACKAGE_NAME}.tgz"
+                peer lifecycle chaincode install /tmp/${PACKAGE_NAME}.tgz
                 
                 # Verify installation
-                INSTALLED_CC=$(kubectl exec -n {{ .Release.Namespace }} $PEER_POD -c {{ .Values.peer.name }} -- \
-                  peer lifecycle chaincode queryinstalled -O json | \
+                echo "Verifying chaincode installation..."
+                INSTALLED_CC=$(peer lifecycle chaincode queryinstalled -O json | \
                   jq -r --arg label "${PACKAGE_NAME}" '.installed_chaincodes[]? | select(.label==$label) | .package_id')
                 
                 if [ -n "$INSTALLED_CC" ]; then
@@ -337,14 +353,19 @@ spec:
                   
                   # Store the package ID for future reference
                   {{- if eq .Values.global.vault.type "hashicorp" }}
+                  echo "Storing package ID in vault..."
                   echo "{\"data\":{\"package_id\":\"${INSTALLED_CC}\"}}" > package_id_payload.json
-                  vaultBevelFunc 'write' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/chaincodes/${CHAINCODE_NAME}/package_id/v${CHAINCODE_VERSION}" 'package_id_payload.json'
+                  vaultBevelFunc 'write' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/chaincodes/${CHAINCODE_NAME}/v${CHAINCODE_VERSION}/package_id" 'package_id_payload.json'
                   {{- else }}
+                  echo "Storing package ID in Kubernetes secret..."
                   kubectl create secret generic ${PACKAGE_NAME}-package-id \
                     --namespace {{ .Release.Namespace }} \
-                    --from-literal=package_id="${INSTALLED_CC}" \
-                    --dry-run=client -o yaml | kubectl apply -f -
+                    --from-literal=package_id="${INSTALLED_CC}"
                   {{- end }}
+                  
+                  # Display installed chaincodes for verification
+                  echo "Current installed chaincodes:"
+                  peer lifecycle chaincode queryinstalled
                 else
                   echo "Error: Chaincode installation failed"
                   exit 1
